modLoader = 'lowcodefml'
loaderVersion = '[40,)'
license = 'LicenseRef-All-Rights-Reserved'
showAsResourcePack = false
mods = [
	{
		modId = 'mr_more_crafts_and_stuff',
		version = '1.0',
		displayName = 'More Crafts and Stuff',
		description = 'Add some crafts using many_more_ores_and_crafts's ores mod.',
		logoFile = 'pack.png',
		authors = 'Bmo_289',
		displayURL = 'https://modrinth.com'
	},
]